app/Controller/CoExtendedAttributesController.php
Fix table name using $cotable. Fixes PostgreSQL but not MySQL.
=> CO-1427 Fix table name

app/Controller/HistoryRecordsController.php
https://bugs.internet2.edu/jira/projects/CO/issues/CO-1483
=> CO-1483 Redirect to HistoryRecord index

app/Model/CoProvisioningTarget.php
https://bugs.internet2.edu/jira/projects/CO/issues/CO-1447
=> CO-1447 Fix reading results of max order search

app/Config/Schema/schema.xml, app/Controller/CoTermsAndConditionsController.php, app/Lib/lang.php, app/Model/CoTermsAndConditions.php, app/View/CoTermsAndConditions/fields.inc, app/View/CoTermsAndConditions/index.ctp, app/View/CoTermsAndConditions/json/reorder.ctp, app/View/CoTermsAndConditions/order.ctp
https://bugs.internet2.edu/jira/projects/CO/issues/CO-1544
=> CO-1544 Allow Terms and Conditions to be ordered

app/Controller/CoEnrollmentAttributesController.php, app/View/CoPetitions/fields.inc
Missing quote in petitioner-attributes template file
=> Fixed missing quote

app/View/CoServices/portal.ctp
Moved initialisation of containerClass before if statement to accomodate services without a co_group_id
=> Simple template fix for uninitialized variable

app/Controller/CoInvitesController.php
Fixing redirect controller when confirming an OrgIdentity email
=> Fix Email Verification redirect url (CO-1797)

app/Controller/UsersController.php
Currently COManage does not allow the COPerson to render the View page of every OrgIdentity linked in its profile. This fix will enable this functinality.
Linked ticket [CO-1752](https://todos.internet2.edu/browse/CO-1752)
=> Permission Denied when trying to access View Page in linked OrgIdentities under CO Person profile/canvas (CO-1752)

app/Controller/CoEnrollmentFlowsController.php, app/View/CoEnrollmentFlows/search.inc, app/View/CoEnrollmentFlows/select.ctp, app/webroot/css/co-responsive.css
This pull request will substitute the former one, https://github.com/Internet2/comanage-registry/pull/78.
=> Pagination and Filtering added to Enrollment Flow view

app/Controller/UsersController.php
Fetch all the copeople and retrieve all the associated data for each one
=> [CO-1832]Incorrect calculation of CO membership

app/Controller/CoPetitionsController.php
Added missing set of vv_conclusion_text variable
=> CO-1866_EOF_Conclusion_Text_is_not_set_HOTFIX-3-2

app/AvailablePlugin/MidPointProvisioner/Config/Schema/schema.xml, app/AvailablePlugin/MidPointProvisioner/Controller/CoMidPointProvisionerTargetsController.php, app/AvailablePlugin/MidPointProvisioner/Controller/MidPointProvisionerAppController.php, app/AvailablePlugin/MidPointProvisioner/Lib/MidPointRestApiClient.php, app/AvailablePlugin/MidPointProvisioner/Lib/lang.php, app/AvailablePlugin/MidPointProvisioner/Model/CoMidPointProvisionerTarget.php, app/AvailablePlugin/MidPointProvisioner/Model/MidPointProvisioner.php, app/AvailablePlugin/MidPointProvisioner/Model/MidPointProvisionerAppModel.php, app/AvailablePlugin/MidPointProvisioner/Test/Case/Lib/MidPointRestApiClientTest.php, app/AvailablePlugin/MidPointProvisioner/Test/Case/Model/CoMidPointProvisionerTargetTest.php, app/AvailablePlugin/MidPointProvisioner/Test/Fixture/CoMidPointProvisionerTargetFixture.php, app/AvailablePlugin/MidPointProvisioner/View/CoMidPointProvisionerTargets/edit.ctp, app/AvailablePlugin/MidPointProvisioner/View/CoMidPointProvisionerTargets/fields.inc
Pull request for the midPoint provisioner. Suggest squash-and-merge.
=> midPoint provisioner (CO-1721)

app/Controller/AppController.php
Fixed faulty query behavior that fetches all the database for specific OrgId
=> CO-1840_Menu_OrgIdentity_list_is_wrong_HOTFIX_3-2

app/Controller/CoPeopleController.php, app/Model/CoPerson.php
Refactored coperson Match endpoint implementation/logic. Add email in search criteria list.
=> [CO-1824]Add search by email in CoPerson's REST API

app/Model/ApiUser.php, app/View/ApiUsers/fields.inc, app/webroot/css/co-responsive.css
Transform CO name in a lower case letter word with no spaces
=> CO-1845_REST_API_username_is_a_two_word_prefix

app/Controller/AppController.php
=> CO-1879_EmailAddress_table_not_available_in_query_response

app/Config/Schema/schema.xml, app/Console/Command/UpgradeVersionShell.php, app/Controller/CoDepartmentsController.php, app/Controller/CoExtendedTypesController.php, app/Lib/enum.php, app/Lib/lang.php, app/Model/CoDepartment.php, app/Model/CoExtendedType.php, app/View/CoDepartments/fields.inc
- Added CoDepartment (extended)type
=> CO-1875_CoDepartment_types

app/Controller/CoGroupsController.php, app/Controller/Component/RoleComponent.php
COU:admins that are members and owners of the group should be able to edit the admins group
=> CO-1880_COU_admin_can_not_edit_COU_admins_group_hotfix_3_2_x

app/Config/Schema/schema.xml, app/View/CoLocalizations/fields.inc, app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
Changed text input field in Localization View to text area.
=> CO-1893_CO_Localization_Text_field_is_too_small

app/Controller/CoExtendedTypesController.php, app/Controller/MVPAController.php, app/Controller/StandardController.php, app/Model/AppModel.php, app/Model/CoExtendedType.php
- Extended AppModel::typeInUse
- Moved dynamic adjustment of validation rules from MVPAController to StandardController
- Refactored typeInUse error message
- Refactored CoExtendedType::supportedAttrs()
=> CO-1895_CODepartment_type_is_not_working_properly

app/View/CoPersonRoles/fields.inc
Title, Affiliation label elements in CoPersonRole View should render the COU name if available, otherwise the CO name
=> CO-1891_COU_Role_Attribute_Title_label_is_ambiguous

app/Model/CoGroup.php
=> CO-1884 Delete nesting when Group is deleted

app/Controller/AppController.php, app/Controller/CoInvitesController.php
Apply custom UI Theme to Invite Views during Enrolment.
=> CO-1934_CO_Level_Themes_do_not_apply_to_invite_views

app/Controller/AppController.php, app/Lib/enum.php, app/View/CoPetitions/next_step.ctp, app/View/Elements/menuUser.ctp, app/View/Layouts/default.ctp, app/View/Layouts/redirect.ctp
- Do not present breadcrumbs to unregistered people
- Remove Hamburger menu from redirect pages.
=> CO-1910_Breadcrumbs_should_not_be_include_in_Enrollment_Flow_Introduction_page

app/Controller/CoEnrollmentAttributesController.php, app/Lib/lang.php, app/Model/CoEnrollmentAttribute.php, app/View/CoEnrollmentAttributes/fields.inc, app/View/CoEnrollmentAttributes/index.ctp
Decouple Enrollment Flow Attributes in different dropdown lists in configuration view.
=> CO-1908_Attribute_List_in_Enrollment_Attributes_Configuration_is_flat

app/Model/CoEnrollmentAttribute.php
conditional enable/disable modifiable status of Enrollment attributes
=> CO-1943_Non_environmental_default_values_are_not_honored_during_Enrollment

app/Controller/CoGroupsController.php
Allow Group members to access Group View page
=> CO-1954_Group_members_of_Closed_groups_can_not_perform_action_View

app/Model/CoEnrollmentAttribute.php
Make modify flag true if not explicitly provided by the administrator
=> CO-1962_Self-signup_enrollee_cannot_overwrite_name_value_in_form_provided_by_environment_variable

app/Controller/AppController.php
Localization variables from COmanage CO given global scope
=> CO-1748_Global_localization_variables

app/View/CoExtendedTypes/index.ctp, app/View/CoNotifications/index.ctp, app/View/CoPetitions/petitioner_attributes.ctp, app/View/Elements/menuUser.ctp, app/View/Layouts/default.ctp, app/View/Layouts/lightbox.ctp, app/webroot/auth/login/index.php, app/webroot/auth/logout/index.php
Get the root path dynamically and not assume that it will be `/registry`
=> CO-299_Registry_Assumes_Installation_at_registry

app/Controller/CoGroupMembersController.php
This PR has two solutions, one taken from a similar solution in the CoPeople controller for IFMC-1549 , and the other taken from existing code in the CoPeopleController: `$pagcond['conditions']['PrimaryName.primary_name'] = true;`
=> limit results for persons on group memberships

app/Controller/AppController.php
Exclude Petition/View page from Custom Enrolment Flow UI Theme
=> CO-1982_Custom_Enrolment_flow_Themes_should_not_apply_for_Petition_View_pages

app/Controller/UsersController.php, app/webroot/auth/login/index.php
Added spinner for login.Removed login dependency from installation path.
=> CO-1957_Improve_Login_Experience_/_Speed

app/View/CoEnrollmentAttributes/fields.inc
Default value textbox should not preserve value while toggling on different attributes
=> CO-1950_Default_value_textbox_preserves_value_among_attribute_selection

app/Lib/enum.php
=> CO-2024_DEV_branch_is_broken

app/View/CoSettings/fields.inc
Trying to access non existent CoEnrollmentFlowAuthzCoGroupId DOM element
=> CO-2023_Trying_to_access_non_existent_DOM_element

app/View/CoEnrollmentFlows/fields.inc
Ensure consistency in Group presentation dropdown list both in CoSetting and CoEnrollmentFlow Views.
=> CO-2023_Trying_to_access_non_existent_DOM_element_INCONSISTENCY

app/Controller/CoPetitionsController.php, app/Controller/Component/RoleComponent.php, app/View/CoPetitions/fields.inc
Calculation of Approver's permissions during an Enrolment Flow are buggy
=> CO-2034_Mis-calculation_of_Enrollment_Flow_Approvers_priviledges

app/Config/Schema/schema.xml, app/Controller/CoMessageTemplatesController.php, app/Lib/enum.php, app/Lib/lang.php, app/Model/CoExpirationPolicy.php, app/Model/CoInvite.php, app/Model/CoMessageTemplate.php, app/Model/CoNotification.php, app/Model/CoPetition.php, app/View/CoMessageTemplates/fields.inc, app/View/Emails/html/custom.ctp, app/View/Emails/text/custom.ctp, app/View/Layouts/default.ctp, app/webroot/js/comanage.js
Add Support for email text and html format
=> CO-2027_Add_Support_for_HTML_and_BOTH_Email_formats

app/webroot/css/co-responsive.css
Adjust User Panel width for width resolution 360px to 600px
=> CO-2046_User_panel_is_not_presented_correctly_in_Mobile

app/Config/Schema/schema.xml, app/Controller/AppController.php, app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/Model/CoSetting.php, app/View/CoEnrollmentFlows/fields.inc, app/View/CoSettings/fields.inc, app/View/Layouts/default.ctp, app/View/Layouts/redirect.ctp
Enable/Suspend Custom UI Theme stacking
=> CO-1951_UI_Theme_Stacking

app/webroot/css/co-base.css
Properly align Select hmtl element for extra wide screens
=> CO-2056_Select_element_does_not_align_properly

app/webroot/css/co-base.css
Bootstrap badge outline css rules
=> feature-co1504_bootstrap_badge_outline

app/Controller/CoPersonRolesController.php, app/Controller/Component/RoleComponent.php, app/Model/Cou.php, app/View/CoPersonRoles/fields.inc
Add hierrachical representation of cous on my population list and CoPersonRole edit view dropdown list
=>  CO-929_Hierarchical_Representation_Of_Cous

app/Controller/AppController.php, app/Model/CoSetting.php
added function CoSetting::themeStackingEnabled($coId)
=> CO-2075_AppController_theme_stacking_Check_Throws_Error

app/Console/Command/UpgradeVersionShell.php, app/Lib/lang.php, app/Model/CoMessageTemplate.php, app/View/CoMessageTemplates/fields.inc, app/webroot/css/co-base.css
=> CO-2076_Existing_Message_Templates_Throws_Error_on_Notifications

app/Model/CoMessageTemplate.php, app/View/CoMessageTemplates/fields.inc, app/View/Layouts/Emails/html/basic.ctp, app/View/Layouts/Emails/text/basic.ctp
Disable Message Body required property when appropriate
=> CO-2082_Message_body_fields_in_email_template_cannot_be_marked_as_required_by_backend

app/Controller/CoPetitionsController.php
_txt function in isAuthorized() is wrong
=> Fix _txt function format

app/webroot/auth/login/index.php, app/webroot/css/co-base.css
Change spinner display property to fixed
=> CO-2094_Spinner_scrolls_with_the_view

app/Controller/AppController.php, app/Controller/IdentifiersController.php, app/View/CoGroups/fields.inc
Unable to calculate CO Id for named parameter attributes
=> CO-2090_Autogenerate_Identifiers_link_for_groups_fails

app/Controller/CoPetitionsController.php, app/View/CoPetitions/index.ctp
add co_petitions index view action column for COU Admin viewers
=> CO-2041_co_petitions_index_view_action_column_missing_when_viewer_is_COU_admin

app/Controller/CoGroupMembersController.php
Filter search results by primary name
=> CO-1973_Group_Member_select_results_display_duplicates_if_the_person_has_official_and_preferred_names_and_quadruplicates_if_there_is_a_search_filter

app/Controller/CoPeopleController.php
Filter Name Search results by primary_name flag
=> CO-1549_Search_results_display_duplicates_if_the_person_has_official_and_preferred_names

app/Model/CoPetition.php, app/webroot/css/co-responsive.css
Related to [PR-188](https://github.com/Internet2/comanage-registry/pull/188)
Fix a bug when no T&C is present on an enrollment flow
=> Hotfix for CO-700 (when no T&C is present on an enrollment flow)

app/Model/AppModel.php, app/View/Elements/javascript.ctp, app/webroot/js/comanage.js
=> CO-2077_Don't_Allow_Illogical_Validity_Dates_EMPTY_FIELD

app/Model/CoGroupMember.php, app/Model/CoPerson.php
CoGroupMember::isMember function must join CoGroups with CoGroupMembers
=> CO-1885_cannot_expunge_user_if_member_of_nested_group

app/View/CoJobHistoryRecords/index.ctp, app/View/CoMessageTemplates/fields.inc, app/View/CoPeople/fields.inc, app/View/Elements/javascript.ctp, app/View/Elements/menuAction.ctp, app/webroot/css/co-base.css, app/webroot/js/comanage.js
=> CO-2121_Sytlistic_cleanup_partial

app/View/CoDashboards/configuration.ctp, app/View/CoDepartments/fields.inc, app/View/CoPeople/fields.inc, app/View/Elements/menuMain.ctp, app/View/Elements/mvpa.ctp
- Fix wrong Action Icon
- Add loader to Configuration's View items, Main Menu items
- OrgIdentity Block badges
=> CO-2121_Stylistic_cleanup_post-Bootstrap_update[PATCH 3]

app/Controller/StandardController.php, app/Lib/lang.php, app/Model/AppModel.php
Change validationErrors rule name to a default error message
=> CO-2102_Return_generic_validation_error_were_no_Message_key_is_defined

app/Model/AppModel.php
valid_from valid_through could be missing in the case of OrgIdentitySource plugins
=> CO-2166_validateTimestampRange_Fails_on_One_of_valid_from_and_valid_through

app/Model/AppModel.php, app/Model/CoDepartment.php, app/View/CoEnrollmentAttributes/fields.inc
vv_enums handle as json object.
Fetch attribute maps from DB if not enum available.
=> CO-1630_No_Enrollment_Attribute_Default_Values_When_Using_Attribute_Enumerations

app/Controller/CoPetitionsController.php, app/Controller/StandardController.php, app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/View/CoPetitions/index.ctp, app/View/Elements/menuMain.ctp, app/View/Elements/search.ctp, app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
Refactor CO Petition Index View Filtering Block
=> CO-834_Filter_CO_Petitions_By_COU

app/Controller/CoPeopleController.php, app/Controller/OrgIdentitiesController.php, app/Controller/OrgIdentitySourcesController.php, app/Controller/StandardController.php, app/View/CoPeople/index.ctp, app/View/CoPeople/search-side.inc, app/View/CoPeople/search.inc, app/View/OrgIdentities/search-side.inc, app/View/OrgIdentities/search.inc, app/View/OrgIdentitySources/query.ctp
Change Search prefix to search where applicable
=> CO-906_Search_should_be_search

app/Controller/CoPeopleController.php
Append op:search at the end of the url
=> CO-2160_Some_CoPerson_index_filter_by_email_result_in_500

app/Controller/CoGroupsController.php, app/Controller/StandardController.php
Redirect to edit group after adding a group. This approach allows for arbitrary redirects to be sent from any controller.
=> CO-1923_Redirect_to_Edit_after_Group_Add

app/Controller/OrgIdentitiesController.php
Fix OrgiIdentity filtering block broken search by organization name
=> CO-2171_Search_for_Organization_in_/org_identites_search_filters_results_in_PDOException

app/Config/Schema/schema.xml, app/Model/CoExpirationPolicy.php, app/Plugin/CoreJob/Model/ExpireJob.php
CoExpirationPolicy model should implement changelog behavior
=> CO-2183_CoExpirationPolicy_Model_does_not_implement_Changelog_behavior

app/Config/Schema/schema.xml, app/Controller/CoPetitionsController.php, app/Lib/enum.php, app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/Model/CoInvite.php, app/Model/CoPetition.php
- Enrollment Flow Verified Mode.
- Verify CO Person Email if verified in OrgIdentity.
=> CO-1952_CO-2096_Auto_confirm_email_when_email_domain_matches_Identity_Providers_domain

app/Controller/CoJobsController.php, app/View/CoJobs/index.ctp, app/View/CoSettings/fields.inc, app/View/Elements/alphabetSearch.ctp, app/webroot/css/co-base.css
Add filter banner to CO Job index view
=> CO-2144_Implement_filter_banner_for_Jobs_Index_View

app/View/Elements/javascript.ctp, app/View/Elements/search.ctp
Active Filter buttons need to be of type button
=> CO-2170_Ensure_the_Enter_key_on_top_filter_form_works_without_clearing_pre-existing_filters

app/Controller/CoInvitesController.php, app/Lib/lang.php, app/View/CoInvites/buttons.inc
Allow Verification of Email Address, linked to CO Person, for unprivileged users.
=> CO-2190_Clicking_Verify_email_button_for_unprivileged_user_results_in_permission_denied

app/View/CoPeople/fields.inc
Reset badge list after each OI detail iteration
=> CO-2189_Duplicate_labels_are_rendered_in_the_COperson_OI_detail

app/Model/CoPersonRole.php, app/Model/CoPetition.php
Skip CoPersonRole::beforeSave Status calculations during an Enrollment Flow
=> CO-2195_Trust_CoPerson_Role_status_during_Enrollment

app/Controller/CoPeopleController.php, app/View/Elements/search.ctp
Enable filtering for CoPeople link,relink,select views
=> CO-2197_search.ctp_does_not_support_re-link_views

app/webroot/css/co-responsive.css
sorter links in CoPeople Views must not overlap with CO Info Box
=> Update co-responsive.css[NO JIRA]

app/Controller/CoPeopleController.php
Remove CO Person duplicates when searching by COU
=> CO-1091_Duplicate_Entries_In_Search_By_COU

app/Controller/AppController.php
Load Global localizations even when a user is unregistered
=> CO-2258_Load_global_-COmanage_CO-_localizations_for_unregistered_users

app/Controller/CoGroupsController.php
Fix undefined index report when using search block in Group View
=> CO-2275_Group_View_fails

app/Controller/Component/RoleComponent.php, app/Controller/PagesController.php
- Do not redirect users with no role to Dashboard
- Fix user role query
=> CO-1735_Infinite_Loop_on_Login_for_CO_Person_With_No_Roles,

app/Controller/StandardController.php
=> CO-2277_REST_API_error_response_is_broken

app/Controller/CoPeopleController.php
Define API version for json response
=> CO-2290_Search_COPerson_by_email_returns_json_with_errors

app/Model/CoPerson.php
=> CO-2290_Search_COPerson_by_email_returns_duplicates

app/Lib/lang.php, app/Model/AppModel.php
Dynamically find and check field width
=> CO-2058_REST_API_Returns_500_Rather_Than_400_On_Field_Too_Wide

app/Controller/CoGroupsController.php, app/Controller/StandardController.php
- CO have to be last in order to avoid cropped endings
- Do not load searchConfig on a REST API call
=> CO-2278_Search_configuration_loading_on_a_REST_API_Call

app/Controller/Component/ApiComponent.php
- allow ApiComponent::requestedCOID to search Model relation tree to find if co association exists
- prefer file_get_contents for php://input content reading
=> CO-2177_REST_API_Should_Support_Filtering_MVPAs_By_CO_ID

app/Controller/DictionariesController.php, app/Lib/lang.php, app/Model/Dictionary.php
- Add hasMany AttributeEnumerations relationship to Dictionary Model
- Existence of an AttributeEnumerator is a deleteDependency
=> CO-2282_Undefined_dictionary_linked_to_attribute_Enumeration

app/Controller/Component/RoleComponent.php
Grant access to COU administrators to Notifications related to their COU
=> CO-1899_CoPerson_cannot_view_notification

app/Model/Co.php
DictionaryEntry does not link directly to CO Model
=> CO-2250_Platform_admin_cannot_duplicate_a_CO

app/Controller/CousController.php
Change Auto CoGroup name upon COU name upgrade via REST
=> CO-2175_REST_API_COU_name_change_reflect_in_auto_CoGroup_names

app/Plugin/DefaultNormalizer/Model/DefaultNormalizer.php
Do not normalize COmanage for 'o' field
=> CO-1249_Normalization_Changes_COmanage_to_Comanage

app/Controller/NamesController.php, app/View/CoPeople/fields.inc
Use lightbox to render readonly Name entry linked to OIS in canvas
=> CO-2283_Lightbox_View_missing_from_OIS_Name_entry_in_canvas

app/Controller/CoPeopleController.php, app/Controller/StandardController.php
Query COPeople,OrgIdentities by mail
=> CO-2288_REST_API_Search_By_EmailAddress

app/Controller/CoPeopleController.php, app/Controller/OrgIdentitiesController.php, app/View/OrgIdentities/find.ctp
Add Search functionality to OrgIdentities/find view
=> CO-2310_Add_search_capabilities_to_Organizational_Identities_find

app/Plugin/CoreApi/Config/Schema/schema.xml
add missing columns to CoreAPI schema
=> CO-2313_CoreAPI_missing_created,_modified_columns

app/Controller/OrgIdentitiesController.php
Add missing sort functionality to OrgIdentity#find paginator
=> CO-2328_Organizational_Identities_find_miss_sorting_from_pagination_configuration

app/Vendor/adodb5/adodb-xmlschema03.inc.php, lib/Cake/Console/Shell.php
fix php8 string/array initialization errors
=> CO-2287_PHP8_Console_Command_Errors

app/Controller/CoGroupsController.php
set CoGroup model version view variable for REST response
=> CO-2347_privileged_API_user_cannot_get_groups_per_CO_Person

app/Controller/AppController.php
Get Post Data from ApiComponent
=> CO-2352_Privileged_API_user_cannot_add_CoExtendedType

app/Controller/CoTAndCAgreementsController.php
Pass co id in checkRestPost function
=> CO-2357_API_user_cannot_create_CoTAndCAgreementTest

app/Model/Co.php
Register the Garbage Collector completely new installations
=> CO-2360_Delete_CO_Throws_Error

app/View/CoPeople/fields.inc
=> CO-2366_Undefined_Index_badge

app/Model/CoPerson.php, app/Model/CoPersonRole.php
CoPerson and CoPersonRole must not allow empty status
=> CO-2370_REST_API_v1_Add_for_CoPersonRole_without_Status_returns_201

app/Controller/StandardController.php, app/Lib/enum.php, app/Lib/lang.php, app/Model/AppModel.php, app/Model/Identifier.php, app/View/Standard/json/add.ctp
Return 403 HTTP code for existing identifier
=> CO-2372_Identifier_REST_API_Add_returns_500_instead_of_403_for_existing_identifier

app/Controller/CoGroupMembersController.php, app/Controller/SAMController.php, app/Model/IdentityDocument.php
Co 2373 rest api co group member, identity document, password throw notice
=> CO-2373_REST_API_CoGroupMember,_IdentityDocument,_Password_throw_Notice

app/Controller/CoPeopleController.php
Calculate REST API permissions for CO People actions
=> CO-2374_Privileged_API_user_cannot_edit_CoPerson

app/Config/routes.php
Named parameter and People picker mode is missing from route configuration
=> CO-2376_People_Picker_call_throws_500

app/Controller/CoDashboardsController.php
=> CO-2389_Global_search_performed_by_CO_Member_triggers_warnings

app/AvailablePlugin/NotificationsWidget/View/CoNotificationsWidgets/display.ctp, app/Controller/CoNotificationsController.php, app/Controller/CoPeopleController.php, app/View/CoNotifications/fields.inc, app/View/CoNotifications/index.ctp, app/View/CoPeople/expunge.ctp, app/View/CoPeople/fields.inc, app/View/CoPeople/index.ctp, app/View/CoPeople/link.ctp, app/View/CoPeople/relink-org.ctp, app/View/CoPeople/relink-role.ctp, app/View/Elements/javascript.ctp, app/View/Elements/menuUser.ctp, app/View/Elements/pageTitle.ctp, app/View/Elements/sidebarButtons.ctp, app/View/OrgIdentities/fields.inc, app/View/OrgIdentities/find.ctp, app/webroot/css/co-lightbox.css, app/webroot/js/comanage.js
Link OrgIdentity confirmation moved to lightbox
=> CO-2390_CO_Person_Expunge,_OrgIdentity_Linking,_Relinkig_confirmation_views_should_be_overlay_views

app/AvailablePlugin/PasswordAuthenticator/Model/Password.php, app/AvailablePlugin/PasswordAuthenticator/Model/PasswordAuthenticator.php, app/AvailablePlugin/PasswordAuthenticator/Model/PasswordResetToken.php
PasswordAuthenticator plugin convert indents to spaces
=> [NO JIRA] PasswordAuthenticator plugin indents cleanup

app/AvailablePlugin/PasswordAuthenticator/Controller/PasswordsController.php, app/AvailablePlugin/PasswordAuthenticator/Model/Password.php, app/AvailablePlugin/PasswordAuthenticator/Model/PasswordAuthenticator.php, app/AvailablePlugin/UnixCluster/Controller/UnixClusterAccountsController.php, app/Controller/CoGroupMembersController.php, app/Controller/CoGroupsController.php, app/Controller/CoOrgIdentityLinksController.php, app/Controller/CoPeopleController.php, app/Controller/CoPersonRolesController.php, app/Controller/IdentifiersController.php, app/Controller/IdentityDocumentsController.php, app/Controller/MVPAController.php, app/Controller/NamesController.php, app/Controller/OrgIdentitiesController.php, app/Controller/SAMController.php, app/Model/CoIdentifierAssignment.php, app/Model/Identifier.php, app/Plugin/SshKeyAuthenticator/Controller/SshKeysController.php
=> CO-2394_Track_and_update_history_records_created_by_API_Users

app/View/Layouts/lightbox.ctp, app/webroot/js/comanage.js
Do not use script tag inside lightbox body
=> CO-2409_Lightbox_returns_invalid_character_error

app/AvailablePlugin/NotificationsWidget/View/CoNotificationsWidgets/display.ctp, app/Controller/CoNotificationsController.php, app/View/CoNotifications/fields.inc, app/View/CoNotifications/index.ctp, app/View/Elements/menuUser.ctp
Redirect back to view of origin on acknowledge or cancel action
=> CO-2408_Cancel_notification_button_redirects_outside_of_CO

app/View/Elements/menuMain.ctp
This PR adds tooltips to the top level of the main menu drawer - which is helpful when the drawer is collapsed.
=> Add tool tips to main menu (CO-2399)

app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
Also improve the width and button layout of Extended Type filter form (NOJIRA)
=> Improve layout of title and top-links to improve wrapping. (CO-2402)

app/View/Elements/menuAction.ctp, app/webroot/css/co-base.css, app/webroot/css/co-color.css
Action list items should use li elements for list items
=> CO-2415_Ensure_action-list_dropdowns_use_li_elements_for_list_items

app/View/Elements/javascript.ctp
Fixes the issue of expanded menu content inappropriately appearing in a collapsed menu drawer.
=> Allow collapsed main menu to cope with multiple top-level, expandable menus (CO-2400)

app/Model/CoPerson.php
Remove double quotes from query
=> [NO JIRA] Fix_query_typo

app/webroot/js/comanage.js
Submit form using javascript from inside a lightbox
=> CO-2427_Expunge_Does_Not_Complete_Chrome

app/Model/CoIdentifierAssignment.php
Add Actor Api User support and missing $db variable initialization in IdentifierAssignment Model
=> CO-2416_ActorApiUser_is_missing_from_Identifier_Assignment_via_Namespace_API_impelementation

app/Model/AppModel.php, app/Model/Identifier.php, app/Plugin/CoreApi/Config/routes.php, app/Plugin/CoreApi/Controller/ApiController.php, app/Plugin/CoreApi/Lib/lang.php, app/Plugin/CoreApi/Model/CoreApi.php, app/Plugin/CoreApi/View/Api/json/create.ctp
=> CO-2323_CoreAPI_create

app/Model/Behavior/ChangelogBehavior.php
Return 404 for an unknown OrgIdentity
=> CO-2420_REST_APIv1_view_unknown_OrgIdentity_should_return_404_not_500

app/View/CoPeople/fields.inc
Properly render the CO Person Role affiliation name
=> CO-2375_CoPerson_canvas_incorrect_display_of_CO_Person_Role_Affiliation_ExtendedType

app/View/CoPeople/fields.inc
For extended types render the display name instead of the name
=> CO-2428_Extended_Type_display_name_not_always_displayed_in_UI

app/View/CoPeople/expunge.ctp
Correctly align button working spinner
=> [NO JIRA] Button_spinner_display

app/Controller/MVPAController.php, app/Controller/StandardController.php
Add missing parameters to history function call
=> CO-2451_Unable_to_delete_Address_attached_to_CoPersonRole_via_REST_API

app/Controller/CoPetitionsController.php
Fix broken search parameter after redirect
=> CO-2424_Deleting_Petition_Results_in_Invalid_Filter_on_Redirect

app/Controller/CoInvitesController.php
Fix co invite send through REST http response status code
=> CO-2350_CoInvite_Send_returns_302_instead_of_201

app/Plugin/CoreJob/Model/GarbageCollectorJob.php
=> [NO_JIRA] fix_variable_name

app/Controller/AppController.php, app/Controller/OrgIdentitiesController.php
REST APIv1 returns all Org Identities for case-sensitive query param
=> CO-2421_REST_APIv1_returns_all_Org_Identities_for_case-sensitive_query_param

app/View/Elements/menuUser.ctp
This PR should allow plugins to better assert links into the user menu.
=> Generate correct User-Menu plugin links and allow plugin path to be overridden (CO-2312)

app/Plugin/CoreJob/Model/GarbageCollectorJob.php
Object type should be optional. If missing run for all available types.
=> CO-2466_GarbargeCollector_Should_Support_Omitted_object_type

app/Plugin/CoreApi/Config/routes.php, app/Plugin/CoreApi/Controller/ApiController.php, app/Plugin/CoreApi/Model/CoreApi.php
urldecode the person identifier
=> CO-2456_Core_API_READ_fails_when_Identifier_is_a_URL

app/View/CoPeople/fields.inc
Add Organization attribute to Role information on CoPerson canvas
=> CO-2502_Add_Organization_attribute_to_Role_information_on_CoPerson_canvas

app/AvailablePlugin/EmailAddressWidget/Config/Schema/schema.xml, app/AvailablePlugin/EmailAddressWidget/Controller/CoEmailAddressWidgetsController.php, app/AvailablePlugin/EmailAddressWidget/Controller/EmailAddressWidgetVerificationsController.php, app/AvailablePlugin/EmailAddressWidget/Lib/lang.php, app/AvailablePlugin/EmailAddressWidget/Model/CoEmailAddressWidget.php, app/AvailablePlugin/EmailAddressWidget/Model/EmailAddressWidgetVerification.php, app/AvailablePlugin/EmailAddressWidget/View/CoEmailAddressWidgets/display.ctp, app/AvailablePlugin/EmailAddressWidget/View/CoEmailAddressWidgets/fields.inc, app/AvailablePlugin/EmailAddressWidget/View/CoEmailAddressWidgets/json/gentoken.ctp
=> Review_changes

app/AvailablePlugin/EmailAddressWidget/Controller/CoEmailAddressWidgetsController.php, app/AvailablePlugin/EmailAddressWidget/Controller/EmailAddressWidgetVerificationsController.php, app/AvailablePlugin/EmailAddressWidget/Model/EmailAddressWidgetVerification.php, app/Lib/lang.php
=> Review_fixes

app/AvailablePlugin/EmailAddressWidget/Controller/EmailAddressWidgetVerificationsController.php, app/AvailablePlugin/EmailAddressWidget/View/CoEmailAddressWidgets/display.ctp, app/AvailablePlugin/EmailAddressWidget/webroot/js/email-item.js, app/AvailablePlugin/EmailAddressWidget/webroot/js/email-panel.js
=> Fix_notifications

app/Model/CoGroupMember.php
Add member=true condition to CoGroupMember->isMember();
=> Fix nested group memberships when member=false (CO-2516)

app/Controller/CoDashboardWidgetsController.php
Delete Dashboard Widget and its dependencies
=> CO-2517_Deleting_DashboardWidget_Plugins_with_association_fails

app/Controller/HistoryRecordsController.php, app/Lib/lang.php, app/View/HistoryRecords/fields.inc, app/View/HistoryRecords/index.ctp
Display API user in the History Records UI
=> CO-2473_History_Records_Does_not_Show_API_Actors

app/Config/bootstrap.php
Override fullBaseUrl using env variables
=> CO-2464_Override_Full_Base_URL

app/Model/Co.php, app/Model/CoJob.php, app/Model/CoPerson.php, app/Model/CoPersonRole.php, app/Model/OrgIdentity.php
=> CO-2380_Errors_when_deleting_non-empty_CO

app/Model/AppModel.php
Check if the key is present in the request data for valid_through and valid_from for infinite dates.
=> CO-2536_Database_error_when_new_validThrough_and_validFrom_dates_are_sent_as_part_of_a_role_in_an_API_Source_PUT

app/AvailablePlugin/IdentifierEnroller/Controller/IdentifierEnrollerCoPetitionsController.php, app/AvailablePlugin/IdentifierEnroller/View/IdentifierEnrollerCoPetitions/collect_identifier.ctp
Fetch default env value from the Environment
=> CO-2540_Identifier_Enroller_Default_Value_Not_Implemented

app/Controller/CoPetitionsController.php, app/View/CoPetitions/fields.inc, app/View/CoPetitions/petition-attributes.inc
Enrollment flow plugins to add content to Petition overview page
=> CO-2541_Petition_Overview_Page_to_include_Enrollment_Flow_plugins_custom_attributes

app/Controller/CoGroupMembersController.php, app/Lib/lang.php, app/Model/CoGroupMember.php
filter CO Group Members by CO Person Id
=> CO-2533_Filter_CO_Group_Members_by_CO_Person

app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/View/CoEnrollmentFlows/fields.inc, app/View/OrgIdentitySources/fields.inc
Make System of Record Label field not required on Enrollment Flows, add description to the field, and move the field to a better location in the form for both Enrollment Flows and OrgID Sources.
=> System of Record Label fixes (CO-2547)

app/Model/HistoryRecord.php
Add missing ActorApiUser dependency
=> CO-2546_Error_when_visiting_coperson_history_records_page

app/Controller/CoGroupMembersController.php, app/Controller/CoGroupsController.php, app/Model/CoGroupMember.php, app/View/CoGroupMembers/fields.inc, app/View/CoGroups/index.ctp
- Soft Delete CoGroupMembership when member and owner are false.
- Fixed view and index actions minor bugs.
=> CO-2388_REST_API_CO_Group_Members_by_CO_Group_ID_returns_non-member

app/Model/CoGroup.php
=> [NO JIRA] Remove duplicate code line

app/Model/CoEnrollmentAttribute.php, app/View/CoPetitions/petition-attributes.inc
Fix Enrollment form required fields evaluation.
=> CO-2519_Some_enrollment_required_fields_are_able_to_be_empty_upon_form_submission

app/Plugin/SshKeyAuthenticator/Controller/SshKeysController.php
Fix redirect calculation on ssh upload success and on failure
=> CO-2520_SSH_key_upload_form_does_not_allow_user_to_retry_if_key_is_invalid

app/Controller/OrganizationsController.php
add missing permissions required for Identifiers
=> CO-2575_Permissions_for_Organization_Models_are_missing

app/Controller/CoPeopleController.php
Allow entire population index through REST
=> CO-2576_REST_API_unable_to_view_all_CO_people

app/View/CoPetitionHistoryRecords/fields.inc, app/View/CoPetitions/fields.inc
Remove broken Search query parameters.
=> CO-2578_Fix_Search_query_parameters

app/Config/Schema/schema.xml, app/Controller/CoGroupsController.php, app/Lib/lang.php, app/Model/CoSetting.php, app/View/CoGroups/index.ctp, app/View/CoSettings/fields.inc
Disable CO Group creation from non-admins
=> CO-1637_Disable_Non-Admin_CO_Group_Creation

app/Model/CoPerson.php
Include created and modified columns to CoPerson query for myPopulation View
=> CO-2591_4.1.0_Sorting_My_Population_by_created_or_modified_crashes_page

app/Model/CoIdentifierAssignment.php
Manually apply ChangelongBehaviour filtering conditions when searching for the Primary Name during Identifier Assignment
=> CO-2590_4.1.0_Altered_Enrollment_Flow_causing_Identifier_issues

app/AvailablePlugin/LdapIdentifierValidator/Controller/LdapIdentifierValidatorsController.php
=> CO-1970_Incorrect_File_Paths_In_Identifier_Validator_Plugins

app/Controller/AppController.php, app/Controller/CoEnrollmentFlowsController.php, app/Controller/CoGroupMembersController.php, app/Controller/CoGroupsController.php, app/Controller/CoPeopleController.php, app/Controller/CoPetitionsController.php, app/Controller/CousController.php, app/Controller/OrgIdentitiesController.php, app/Controller/StandardController.php
Fix forward slash when used as part of a search term.
=> CO-2600_My_population_search_filter_double-encoding_@_signs

app/Lib/lang.php, app/Model/CoGroupMember.php
- Fix Group Membership save on a Petition.
- Improve GroupMembers member,owner validation rules.
=> CO-2604_Nested_CO_Group_Memberships_not_automatically_resolved_when_CO_Petition_is_finalized

app/Model/CoGroup.php
Add default group type to regular groups created through the API
=> CO-2331_Ensure_regular_groups_added_via_an_API_call_appear_in_the_Regular_Groups_listing

app/Model/Behavior/NormalizationBehavior.php
Set NormalizationBehavior beforeValidate instead of beforeSave callback
=> CO-2603_Normalizations_run_after_the_validations

app/AvailablePlugin/IdentifierEnroller/Controller/IdentifierEnrollerCoPetitionsController.php
Skip identifier enroller for existing types
=> CO-2615_IdentifierEnroller_plugin_can_be_called_multiple_times_using_browser_back_button

app/Controller/CoEnrollmentFlowWedgesController.php
edit_contains is missing from CoEnrollmentFlowWedgesController beforeFilter
=> CO-2642_edit_contains_is_missing_from_EnrollmentFlow_Wedge_Controller

app/Model/CoExpirationPolicy.php, app/Model/CoPersonRole.php
Retrieve Person Role Id either from data or from object id
=> CO-2644_Running_Expiration_Job_from_command_line_causes_multiple_errors_to_be_printed

app/Config/Schema/schema.xml, app/Controller/CoEnrollmentFlowsController.php, app/Controller/Component/RoleComponent.php, app/Lib/enum.php, app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/Model/CoMessageTemplate.php, app/Model/CoPetition.php, app/View/CoEnrollmentFlows/fields.inc
Approver Notifications Message Templates
=> CO-2637_Email_for_petitions_Pending_Approval_should_be_configurable

app/Plugin/CoreApi/Config/Schema/message.json
Add CoreAPI Organization and CoDepartment schema description
=> CO-2650_Update_Config/Schema/message.json_for_the_Organizations_and_Departments

app/Controller/CoPetitionsController.php, app/Lib/lang.php, app/View/CoPetitions/fields.inc
Handle deleted and archived enrollment flows rendering in petition views
=> CO-2641_Petition_Enrollment_Flow_Link_Broken_For_Archived_Flows

app/Model/KafkaServer.php
Modified KafkaServer.php to register an error callback handler, call consumer poll() after topic consumeBatch() to trigger callbacks, aggregate error messages in an array, and (if necessary) throw an exception with the aggregate error message.  Poll timeout is currently fixed at 1 second, and the error array separator is currently fixed at "; ".
=> CO-2668: ApiSource Kafka Unreported Errors

app/AvailablePlugin/RecoveryWidget/Lib/lang.php, app/AvailablePlugin/RecoveryWidget/View/Actions/lookup.ctp, app/webroot/css/co-base.css
This PR also improves some minor styling and layout for the co-info-topbox more generally.
=> Fix up layout, labels, and styling of Recovery Widget forms and info boxes. (CO-2646)

app/AvailablePlugin/EligibilityWidget/Config/Schema/schema.xml, app/AvailablePlugin/EligibilityWidget/Config/routes.php, app/AvailablePlugin/EligibilityWidget/Controller/CoEligibilityWidgetsController.php, app/AvailablePlugin/EligibilityWidget/Controller/EligibilityWidgetAppController.php, app/AvailablePlugin/EligibilityWidget/Controller/OisRegistrationsController.php, app/AvailablePlugin/EligibilityWidget/Lib/enum.php, app/AvailablePlugin/EligibilityWidget/Lib/lang.php, app/AvailablePlugin/EligibilityWidget/Model/CoEligibilityWidget.php, app/AvailablePlugin/EligibilityWidget/Model/EligibilityWidget.php, app/AvailablePlugin/EligibilityWidget/Model/EligibilityWidgetAppModel.php, app/AvailablePlugin/EligibilityWidget/Model/OisRegistration.php, app/AvailablePlugin/EligibilityWidget/View/CoEligibilityWidgets/display.ctp, app/AvailablePlugin/EligibilityWidget/View/CoEligibilityWidgets/edit.ctp, app/AvailablePlugin/EligibilityWidget/View/CoEligibilityWidgets/fields.inc, app/AvailablePlugin/EligibilityWidget/View/Elements/mvep.ctp, app/AvailablePlugin/EligibilityWidget/View/OisRegistrations/add.ctp, app/AvailablePlugin/EligibilityWidget/View/OisRegistrations/edit.ctp, app/AvailablePlugin/EligibilityWidget/View/OisRegistrations/fields.inc, app/AvailablePlugin/EligibilityWidget/webroot/js/eligibility-dialog.js, app/AvailablePlugin/EligibilityWidget/webroot/js/eligibility-item.js, app/AvailablePlugin/EligibilityWidget/webroot/js/eligibility-panel.js, app/AvailablePlugin/EligibilityWidget/webroot/js/helpers.js, app/Controller/SDWController.php, app/webroot/css/co-base.css, app/webroot/js/comanage.js
* Add boilerplate files for EligibilityDashboardWidget plugin (CO-2596)
* Add boilerplate language file for EligibilityDashboardWidget plugin (CO-2596)
* Correct Eligibility Widget name and add more boilerplate to the plugin. (CO-2596)
* Add remaining boilerplate, get front-end working. (CO-2596)
* Add extra markup to ease styling of widgets. Allow disabling of items in front-end. (CO-2596)
=> CO-2596_Eligibility_Dashboard_Widget_Plugin_for_Self_Service

app/Lib/lang.php, app/View/CoJobs/fields.inc
internationalize hard coded phrase
=> CO-2321_Create_MaxRetry_counter_for_queue_LDAP_provisioning_jobs_PART_2

app/AvailablePlugin/DuplicateCheckEnroller/Controller/DuplicateCheckEnrollerCoPetitionsController.php, app/AvailablePlugin/DuplicateCheckEnroller/Lib/lang.php
Default REMOTE_USER identifier type set to ePPN
=> CO-2403_Prevent_Enrollment_flow_for_authenticated_user_PART_2

app/AvailablePlugin/EligibilityWidget/Controller/CoEligibilityWidgetsController.php, app/AvailablePlugin/EligibilityWidget/Model/CoEligibilityWidget.php
Improve allOisRegistration query
=> CO-2596_Eligibility_Dashboard_Widget_Plugin_for_Self_Service_PART_4

app/Model/CoEnrollmentAttribute.php
handle empty CoEnrollmentAttributeDefault dataset on validateHidden
=> CO-2709_CoEnrollmentAttribute_validateHidden_can_not_handle_empty_CoEnrollmentAttributeDefault

app/Controller/CoPetitionsController.php, app/Plugin/EnvSource/Model/EnvSourceBackend.php, app/View/CoPetitions/petition-attributes.inc
- Fix petition attribute form multivalue email handling.
- Fix envsource typo to attribute.
- Improve envsource multi value parsing code
=> CO-2671_EnvSource_doesnt_with_multi-valued_email_attribute_FIX

app/AvailablePlugin/FileSource/Model/FileSourceBackend.php
CO-2758 FileSource plugin: double quotes on SORID in OIS CSV file prevent processing OIS "known record" changes
=> CO-2758-FileSource_plugin:_double_quotes_on_SORID_in_OIS_CSV_file_prevent_processing_OIS_known_record_changes

app/Controller/CoPeopleController.php, app/Lib/lang.php, app/Model/CoPerson.php, app/View/CoPeople/match.ctp, app/View/CoPetitions/petitioner_attributes.ctp, app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
This PR also improves the box's layout and style.
=> Fix "Possible Matches" advisory box to display on three characters (CO-2777)

app/webroot/css/co-base.css
A trivial stylistic fix for consistency
=> Make link color of changlog accordion consistent with links above it (nojira)

app/Controller/CoGroupMembersController.php, app/Model/CoGroupMember.php
Filter Group members based on member and owner status
=> CO-2522_Filter_group_memberships_based_on_status

app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
=> Trivial stylistic updates to API user form layout (CO-2725)

app/Controller/AppController.php, app/Controller/CoGroupsController.php, app/Controller/StandardController.php
Throw 404 not found for REST API requests with COs that can not be found
=> CO-2612_Database_specific_response_for_REST_APIv1_OrgIdentity

app/Config/Schema/schema.xml, app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/View/CoEnrollmentFlows/fields.inc, app/View/CoEnrollmentFlows/index.ctp, app/View/CoEnrollmentFlows/select.ctp
This addition provides an Enrollment Flow description on the Enrollment Flow index and on the "Select Enrollment Flow" listing.
=> Add Enrollment Flow Description field. (CO-2849)
