Internet2/comanage-registry

app/View/OrgIdentities/search.inc
Selecting an Organizational Identity Source automatically submits the form so that clicking submit would therefore submit twice and likely break CakePHP's csrf checks.
=> CO-1362 Submit form once

app/AvailablePlugin/LdapServiceTokenProvisioner/Model/CoLdapServiceTokenProvisionerTarget.php
co_ldap_provisioner_target should be co_ldap_provisioner_target_id.  
Fixes:  provisioning operation comes back successful in GUI but nothing is provisioned to LDAP.  Logs in error.log:
Notice: Notice (8): Undefined index: co_ldap_provisioner_target in [/srv/comanage/comanage-registry-2.0.1/app/AvailablePlugin/LdapServiceTokenProvisioner/Model/CoLdapServiceTokenProvisionerTarget.php, line 109]
=> Plugin CoLdapServiceTokenProvisioner: Fix provisioning target data array key

app/Plugin/GrouperProvisioner/Model/CoGrouperProvisionerTarget.php
- without continue any exception causes termination of the loop rather than desired continuation to next group
=> GrouperProvisioner - provisionCoPerson: Add continue statement to non-fatal exception catches

app/View/Elements/menuUser.ctp
The Service Token SubMenu does not show.  Now it shows inside the usermenu.
Additionally: The link to the Service Tokens was incorrect, it was missing the 'copersion:' element
=> Fix on ServiceToken submenu

app/Model/CoPersonRole.php
In addition to handling the change of the COU of a CoPersonRole, this commit also handles changing (re-linking) the Person of a CoPersonRole.
=> Remove group memberships if CoPersonRole COU or Person changes (CO-1604)

app/Model/OrgIdentitySource.php
When configuring an OIS like ORCID or EnvSource for 'Full' synchronisation, the code reaches a point (line 1469) where the sourceKeys and knownKeys variables are used in error message output. These variables are not defined at that scope due to a domain-exception of the OIS.
This fix adds a continue after registering the job-fail-history record. As the 'newKeys' variable is empty in this case, the following code would not be executed as well.
Alternatives are to create empty sourceKeys and knownKeys or to put the history record generation inside the try-catch above.
=> syncOIS: Added loop-continue to prevent unknown-variable errors (NOJIRA)

app/View/Elements/menuMain.ctp
the CoServices::parseCOID expects a 'cou' parameter and this is generated elsewhere in the menuMain.ctp template as well. This fix corrects the alleged typo.
=> Fix for CO-1703: wrong URL parameter passed for Services portal

app/Model/CoPetition.php
Typo error: constant variable OISSearchRequired of class EnrollmentOrgIdentityModeEnum
=> Update CoPetition.php - Typo fix

app/View/Elements/menuUser.ctp
In plugin context the link to organizational identity includes the plugin and link does not work.  Similar fix to https://github.com/Internet2/comanage-registry/commit/2fa1d88cdbd4740ffc246fda4dc3b8fa84454694 for this context as well.
=> Fix menuUser Org ID link construction in plugin context

app/AvailablePlugin/AnnouncementsWidget/Controller/CoAnnouncementsController.php
Do not filter out any announcement channels for the add announcement
view when the user is the platform administrator.
=> Render announcement channels for platform admin (CO-1883)

app/Controller/CoDepartmentsController.php, app/Controller/CoPeopleController.php, app/Controller/OrgIdentitiesController.php, app/View/Elements/mvpa.ctp
This PR fixes CO-1856 [Canvas displays View button for identifiers when it should not for non-admins]
The `mvpa.ctp` template renders a link out to an "Identifier" view without checking if the user has permissions to view the url.
There are three pages that use the template to render Identifiers [CoDepartments, CoPeople, and OrgIdentities]. The section of the template that renders the link does so twice, creating a link out of the name of the identifier, and rendering a view button. These sections are also rendered for other types of models besides identifiers, in which case the links are legitimate and should still be shown.
An additional permission 'identifiers' is added to each of the three controllers, following the existing permission pattern found in the controller, and copying the …
=> Co 1856 Canvas displays View button for identifiers when it should not for non-admins

app/Model/CoPerson.php
In testing, I found that the deleteDependent function (used by the CoPerson expunge) gathers up all CoGroupMember records, then deletes them in order.  The beforeDelete throws an error on trying to delete the Parent membership associated with a nested group membership, saying 'Record is already marked deleted.' 
That record was deleted in the afterDelete cleanup associated with the nested group membership's initial deletion - via the syncNestedMembership function (https://github.com/Internet2/comanage-registry/blob/develop/app/Model/CoGroupMember.php#L202).  
So!  To fix this (and also hopefully escape any other delete conflicts on expunge moving forward), let's check whether a record has already been cleaned up before trying to delete it.
=> CO-1885 handle nested group membership on expunge

app/Config/Schema/schema.xml, app/Controller/CoEnrollmentAttributesController.php, app/Controller/CoPersonRolesController.php, app/Controller/CoPetitionsController.php, app/Lib/lang.php, app/Model/CoEnrollmentAttribute.php, app/Model/CoSetting.php, app/View/CoEnrollmentAttributes/fields.inc, app/View/CoPersonRoles/fields.inc, app/View/CoPetitions/petition-attributes.inc, app/View/CoSettings/fields.inc
Added support for Empty COUs
Scenarios tested:
- Add empty named COU manually from inside CO Person's profile
- Choose an empty COU name when configuring an Enrollment flow
- Choose an empty COU name when collecting user's attributes
_Upgrade guide in COmanage wiki should be updated as well._
Should we:
- ~~Advise the user to hide the COU field if s/he has as a default COU name value the empty one and has the modifiable configuration disabled? **- Declined**~~
- enable copying the attributes of a non-empty COU to the empty COU during enrollment? **- Develop this as a Plugin(Enrollee plugin)**
=> CO-951_Allow_Null_COU

app/View/Elements/javascript.ctp, app/View/Elements/menuUser.ctp
CO-1896: This fixes an issue where the form would not submit when a user hit the enter key after entering their search term. It also fixes the fact that the search input was not focused when the dropdown opened up.
=> CO-1896: Fix global search to focus on opening and submit on enter key

app/Model/Behavior/ChangelogBehavior.php, app/Model/CoNotification.php
This beforeFind method is being called prior to running the query in CoNotification on line 609 (https://github.com/Internet2/comanage-registry/blob/develop/app/Model/CoNotification.php#L609).  
This particular elseif is being applied to the nested CoPerson contain (that is included within the CoGroupMember, which is contained within the CoGroup).  Here, a recursive call is done to modifyContain to walk through the CoPerson. 
Prior to the recursive call, the conditions for the CoPerson look like this: 
`'conditions' => array(
'CoPerson.status' => 'A'
)`
After the recursive call, the required new conditions of a null co_person_id and non deleted status are merged with the original Active conditions correctly: 
`'conditions' => array(
'CoPerson.co_person_id' => null,
(int) 0 => …
=> Co 1459 Do Not Send Notifications to Expired Users

app/Controller/CoPeopleController.php
Adding a group by CoPerson.id will ensure that no duplicate records are returned from the CoPerson paginate query.  (Some examples here: https://book.cakephp.org/1.3/en/The-Manual/Common-Tasks-With-CakePHP/Pagination.html#custom-query-pagination)
=> CO-1549 Search results display duplicates if the person has official and preferred names

app/Controller/CoProvisioningTargetsController.php
Enforce the creation of a new instance of plugin's class
=> CO-1988_Deleting_Provisioning_plugin_causes_fatal_error

app/Model/CoIdentifierAssignment.php
Enable default ordering for identifier assignments
=> CO-1965_default_ordering_for_identifier_assignments

app/View/CoPetitions/petition-attributes.inc
This PR fixes a bug at invitation view (when Email Confirmation Mode is "Review" at the enrollment flow)
Related to CO-700 [PR 188](https://github.com/Internet2/comanage-registry/pull/188) & Hotfix [PR 207](https://github.com/Internet2/comanage-registry/pull/207)
=> Hotfix for CO-700 (Fix invitation view)

app/View/CoPeople/fields.inc, app/webroot/css/co-responsive.css
This change separates out the default "Invite" form from the Person Canvas display on CoPeople/fields.inc. The invite form has been restructured similarly to other enrollment flows to fix the layout and make it consistent with our other forms.
=> CO-2129 Fix layout for default Invite form

app/View/Elements/search.ctp
This fixes the "Clear Filters" link appearing when a sort is present but filters in the top search box are not.
=> CO-2168_Show_Clear_Filters_link_only_when_there_ are_filters_to_clear

app/Console/Command/JobShell.php, app/Controller/AppController.php, app/Model/CoLocalization.php
- Move localization loading into CoLocalization Model.
- Jobshell loads localization's
=> CO-2180_Localizations_can_not_be_used_by_Shell_Jobs

app/Controller/AppController.php, app/Model/ApplicationPreference.php, app/View/Elements/javascript.ctp, app/View/Elements/menuMain.ctp, app/View/Layouts/default.ctp, app/webroot/js/comanage.js
Extend Application Preferences for use in all views. This provides a new view variable for accessing a user's application preferences and makes use of them to set the state of the main menu drawer. The legacy use of Cookies for this purpose is deprecated. A JavaScript setter function is added for AJAX PUT of Application Variables.
=> Use Application Preferences for Main Menu state handling (CO-1928)

app/Controller/AppController.php
Allow CO Admins to create Departments on a vanilla COmanage environment
=> CO-2264_CO_Admins_cannot_create_Departments_until_a_CMP_creates_at_least_one

app/View/CoPersonRoles/fields.inc
Enable autofocus for the first field of CoPersonRole add/view form
=> CO-1904_First_field_does_not_have_input_focus_when_manually_adding_new_CO_person_role

app/View/ApiUsers/fields.inc
Do not render input field when the action is view
=> CO-2339_ApiUser_View_missing_action_view_proper_render_for_the_field_priviledged

app/AvailablePlugin/UnixCluster/Model/UnixCluster.php
Fix UnixCluster version and add permissions for priviledged REST API users
=> CO-2353_REST_users_cannot_create_UnixCluster

app/Controller/Component/ApiComponent.php
- prefer file_get_contents for php://input content reading
- allow ApiComponent::requestedCOID to search Model relation tree to find if co association exists
=> CO-2177_REST_API_Should_Support_Filtering_MVPAs_By_CO_ID

app/Model/Co.php
readonly check has to always return boolean
=> CO-2385_Return_404_instead_of_500_when_viewing_unknown_CO_via_API

app/Controller/CoOrgIdentityLinksController.php
Redirect to CO Person Canvas after unlinking an OrgIdentity
=> CO-2337_Unlinking_organizational_identity_should_remain_on_CO_Person_page

app/View/CoPersonRoles/fields.inc
Require selection of COU when "Allow Empty COUs" is not enabled, and make intial state of COU field blank.
=> Add CO Person Role: improve COU select field (CO-2392)

app/Controller/CoPeopleController.php, app/Model/CoPerson.php
Remove MyPopulation search duplicates when a search for partial attribute value fetches the same result more than once
=> CO-2371_Identifier_filter_on_My_Population_page_returns_duplicate_results

app/Lib/lang.php, app/View/Layouts/default.ctp, app/webroot/css/co-base.css
This ensures the entire title banner (with CO Title and COmanage Logo) are hidden when the "Hide Title Banner" checkbox is checked in theme settings.
=> Fix theme setting for "Hide Title" to be "Hide Title Banner" (CO-2414)

app/Lib/lang.php, app/View/CoPeople/fields.inc, app/webroot/css/co-base.css
This PR changes the ID output on Role and OrgID to look like this:
=> Include label for Role and OrgID ID output on Person Canvas (CO-2378)

app/Controller/CoGroupsController.php
Default to current user if copersonid named param is missing for CoGroups Select action
=> CO-2417_CoGroup_Select_action_should_enforce_copersonid_named_parameter_presence

app/AvailablePlugin/PrivacyIdeaAuthenticator/Model/PrivacyIdea.php
allow the user and realm to be displayed as part of the label on the TOTP token in the Authenticatori, as Privacy idea token enrollment policies allow
=> Allow user and realm to be displayed on Authenticator label (CO-2418)

app/Lib/lang.php, app/View/OrgIdentitySources/retrieve.ctp, app/webroot/css/co-base.css
This PR removes the global use of "table-layout: fixed" instead allowing tables to behave using default behavior. It also corrects the problem found in CO-2174 that led to the original change.
As part of this ticket, the "pre" tag has been removed from the view of org identity source records, and a toggle has been put in place to allow users to apply "white-space: pre" to the source record field via that toggle.
=> Restore table-layout to default behavior and fix problem view from original CO-2174 ticket (CO-2398)

app/Lib/lang.php, app/View/CoIdentifierAssignments/fields.inc
This PR sets the default format value to "(#)", ensures that selecting the default in the drop-down sets the field, and removes the empty option.
=> Fix default pattern selection in CoIdentifierAssignements (CO-2391)

app/View/CoEnrollmentAttributes/fields.inc
The call to show() with an options object required easing to be specified. There was negligible perceptual difference between adding easing or removing the object, so the simpler was chosen: the options object was removed. 
(This appears to be the only place in the code where the options object was used in a show() function.)
=> Fix calls to jQuery show() in new enrollment attributes form (CO-2462)

app/Vendor/adodb5/adodb.inc.php, app/Vendor/adodb5/datadict/datadict-postgres.inc.php
- Use IF EXISTS for verfion >9.6
- Skip pg_query default error reporting
- Refactor alter table row queries construction.
=> CO-2538_ADOdb_Throws_Errors_Under_PHP_8.1

app/AvailablePlugin/ElectorDataFilter/Config/Schema/schema.xml, app/AvailablePlugin/ElectorDataFilter/Controller/ElectorDataFiltersController.php, app/AvailablePlugin/ElectorDataFilter/Lib/enum.php, app/AvailablePlugin/ElectorDataFilter/Model/ElectorDataFilter.php, app/AvailablePlugin/ElectorDataFilter/Model/ElectorDataFilterPrecedence.php, app/AvailablePlugin/ElectorDataFilter/View/ElectorDataFilterPrecedences/fields.inc
- After completing the initial "add" page, the user should be redirected back to the same page (to add Precedence rules) rather than the Data Filter plugin index.
- The possible values for attribute_name ("Subject Attribute") should be presented in alphabetical order.
- For consistency with other Enums, tie_break_mode and replacement_mode should be varchar(2)
- Make Precedence form field order optional and allow save
=> CO-2484_Elector_Data_Filter_imrovements

app/Vendor/adodb5/datadict/datadict-postgres.inc.php
ADOdb skip alter step if the table did not contain the row
=> CO-2538_ADOdb_Throws_Errors_Under_PHP_8.1_PART2

app/AvailablePlugin/ApiProvisioner/Model/CoApiProvisionerTarget.php, app/Plugin/LdapProvisioner/Model/CoLdapProvisionerTarget.php
- Refactor obsolete operator in LdapProvisioner plugin
- Abort Person Delete API provisioning in case the Person has no Identifiers
=> CO-2569_Internal_Error_when_expunging_CO_Person

app/Model/Co.php
Skip LdapProvisioner object duplication when there is no configured object
=> CO-2616_Error_when_duplicating_a_CO_that_has_a_configured_SqlProvisioner_Provisioning_Target

app/Controller/CoGroupsController.php
Attempting to view a CoGroup per CO Person with an invalid CoPersonId should return 404
=> CO-2613_Database_specific_response_for_REST_APIv1_CoGroup

app/Model/Behavior/ChangelogBehavior.php, app/Model/CoEnrollmentFlow.php, app/Model/CoGroup.php, app/Model/CoPipeline.php, app/Model/DataFilter.php
- Add missing associations Pipeline,CoEnrollmentFlow,CoGroup,DataFilter
- Changelog Behavior enable correct find for contain equals to true.
=> CO-2697_Add_missing_model_associations._Changelog_behavior_to_support_contain_equal_to_true

app/Model/CoEnrollmentAttribute.php
Special case for sponsor and manager, we want to make sure the modifiable field passes though even if there is no default value
=> CO-2763_Invitation_Enrollment_Flow_-_Field_attribute_pointing_to_Roles-Manager_doesnt_show_field_to_input

app/Config/Schema/schema.xml, app/Lib/enum.php, app/Lib/lang.php, app/Model/CoEnrollmentFlow.php, app/View/CoEnrollmentFlows/fields.inc, app/View/CoPetitions/fields.inc, app/View/CoPetitions/petition-attributes.inc, app/View/Elements/javascript.ctp, app/webroot/css/co-base.css
This pull request implements the ability to allow confirmation for petition approval or denial (always, only on approval, only on denial, or never).
This pull request also allows petitions to be configured to require a comment (with the same possible configurations).
The default for both configurations has been set to "Never" for backward compatibility.
These features are enabled when configuring an Enrollment Flow with Approvers:
The following is an example in which an approver has clicked "Deny", the comment field was marked as required, but the approver did not fill it in:
The following is an example of a confirmation box on Approval:
Configuration allows for these features to be inverted as shown in the configuration screenshot, i.e. require a comment on Approve, a confirmation on …
=> Provide confirmation for petition Approve or Deny (CO-2815)

app/Lib/lang.php, app/View/Layouts/redirect.ctp, app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
This PR adds a simple message above the redirect information box during an enrollment flow that looks like this:
=> Provide "Do not close your browser" message on enrollment flow redirect page (CO-2844)

app/View/CoDashboards/search.ctp, app/View/Elements/javascript.ctp, app/View/Elements/menuUser.ctp, app/View/Elements/searchGlobal.ctp, app/View/Layouts/default.ctp, app/webroot/css/co-base.css, app/webroot/css/co-responsive.css
This PR pulls the top search out of a dropdown and places it to the left near the hamburger menu. The work required reworking the topbar using more modern practices (such as flexbox). The result looks like this:
=> Make top global search significantly more obvious. (CO-2846)

app/AvailablePlugin/SqlProvisioner/Controller/CoSqlProvisionerTargetsController.php, app/AvailablePlugin/SqlProvisioner/Model/CoSqlProvisionerTarget.php
Fix prefix calculation.
Failing to provision Group Members.
Re-sync single SqlProvisionerTarget if provided.
=> CO-2873_SqlProvisioner_Plugin_bugs

app/View/Layouts/redirect.ctp, app/webroot/css/co-base.css
This PR fixes a trivial problem with flex justification within the top bar during redirect to account for if the CO settings contain navigation links or not.
=> Fix top-bar flex layout on redirect page (NOJIRA)

app/webroot/css/co-base.css
This PR ensures that #topLinks items will align to the right even when flex wrapping.
=> Improve #topLinks alignment on flex-wrap (NOJIRA)
